[parity]
chain = "/home/parity/.local/share/io.parity.ethereum/chain_spec.json"
auto_update = "none"
no_download = true

[account]
password = ["/home/parity/.local/share/io.parity.ethereum/password"]

[mining]
force_sealing = true

[rpc]
port = 8545
disable = false
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "traces", "rpc", "shh", "shh_pubsub"]
