[foreign_chain]
rpc_url = "http://foreign-node:8545"
token_contract_address = "0x679131f591b4f369acb8cd8c51e68596806c3916"
bridge_contract_address = "0x18BDC736b23Ff7294BED9fa988a1443357C7B0ed"
event_fetch_start_block_number = 8932341

[home_chain]
rpc_url = "http://home-node:8545"
bridge_contract_address = "0x0000000000000000000000000000000000000401"
event_fetch_start_block_number = 0

[validator_private_key]
keystore_path = "/config/keys/tlbc/account.json"
keystore_password_path = "/config/pass.pwd"
