[foreign_chain]
rpc_url = "http://foreign-node:8545"
token_contract_address = "0x54B06531214AD41DE9d771c10C0030d048d0cC67"
bridge_contract_address = "0x2171Dd4d4F6ca30FeEA8a27b96257A67f371d87A"
event_fetch_start_block_number = 1321331

[home_chain]
rpc_url = "http://home-node:8545"
bridge_contract_address = "0x0000000000000000000000000000000000000401"
event_fetch_start_block_number = 0

[validator_private_key]
keystore_path = "/config/keys/tlbc/account.json"
keystore_password_path = "/config/pass.pwd"
