#! /usr/bin/env python

"""Run pytest with gevent's monkeypatching applied"""

# fmt: off
from gevent import monkey; monkey.patch_all()  # noqa: E402, E702 isort:skip
# fmt: on

import re
import sys

from pytest import main

if __name__ == "__main__":
    sys.argv[0] = re.sub(r"(-script\.pyw?|\.exe)?$", "", sys.argv[0])
    sys.exit(main())
