version: '2.4'
services:

  node_foreign:
    image: parity/parity:v2.5.5-stable
    command:
      - "--light"
      - "--no-download"
      - "--auto-update=none"
      - "--chain=ropsten"
      - "--base-path=/data"
      - "--no-hardware-wallets"
      - "--jsonrpc-interface=all"
      - "--jsonrpc-apis=safe"
      - "--jsonrpc-hosts=all"
      - "--jsonrpc-cors=all"
      - "--no-ipc"
      - "--no-secretstore"
      - "--no-color"
    volumes: ['./data/ropsten:/data']
    ports:
      - "127.0.0.1:8545:8545"
    restart: unless-stopped
    mem_limit: 1G
    mem_reservation: 16M
    stop_grace_period: 3m

  node_home:
    image: trustlines/tlbc-testnet:release4044
    command:
      - "--parity-args"
      - "--light"
      - "--no-hardware-wallets"
      - "--jsonrpc-apis=safe"
      - "--jsonrpc-hosts=all"
      - "--jsonrpc-cors=all"
      - "--no-ipc"
      - "--no-secretstore"
    volumes: ['./data/laika:/home/parity/.local/share/io.parity.ethereum/chains_light']
    ports:
      - "127.0.0.1:8546:8545"
    restart: unless-stopped
    mem_limit: 1G
    mem_reservation: 16M
    stop_grace_period: 3m
