version: '2.4'
services:

  redis:
    image: redis:5.0.5
    command:
      - "redis-server"
      - "--appendonly yes"
    volumes: ['./data/redis:/data']
    restart: unless-stopped
    mem_limit: 1G
    mem_reservation: 16M
    stop_grace_period: 1m
