version: '2.4'
services:

  validator:
    build:
      context: ../../../
      dockerfile: tools/bridge/Dockerfile
    env_file:
      - ../.env
    restart: unless-stopped
    mem_limit: 512M
    mem_reservation: 16M
    stop_grace_period: 30s
