#! /usr/bin/env python

"""Run pytest with gevent's monkeypatching applied"""

from gevent import monkey  # isort:skip

monkey.patch_all()  # noqa: E402 isort:skip

import re
import sys

from pytest import main

if __name__ == "__main__":
    sys.argv[0] = re.sub(r"(-script\.pyw?|\.exe)?$", "", sys.argv[0])
    sys.exit(main())
